### ISSUE TITLE
Call to a member function id() on null in /home/project/omeka-s/modules/Annotate/src/Form/ResourceForm.php:39

### ISSUE THREAD

**Issue by sinanatra** [Daniel-KM/Omeka-S-module-Annotate#7]
Hello,
when i try to edit an annotation i get this error:
```
Error: Call to a member function id() on null in /home/project/omeka-s/modules/Annotate/src/Form/ResourceForm.php:39
Stack trace:
#0 /home/project/omeka-s/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerV3Polyfill.php(323): Annotate\Form\ResourceForm->init()
#1 /home/project/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(780): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit()
#2 /home/project/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate()
#3 /home/project/omeka-s/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get()
#4 /home/project/omeka-s/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php(56): Laminas\ServiceManager\AbstractPluginManager->get()
#5 /home/project/omeka-s/application/src/Mvc/Controller/Plugin/GetForm.php(33): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->get()
#6 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke()
#7 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(275): call_user_func_array()
#8 /home/project/omeka-s/modules/Annotate/src/Controller/Admin/AnnotationController.php(348): Laminas\Mvc\Controller\AbstractController->__call()
#9 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Annotate\Controller\Admin\AnnotationController->editAction()
#10 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#11 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#12 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#13 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#14 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#15 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#16 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#17 /home/project/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#18 {main}
```

**Comment by Daniel-KM** [comment]
It's probably related to the fact you renamed or removed the default resource template "Annotation".

**Comment by Daniel-KM** [comment]
If there was an issue during install, upgrade module Generic to the last version first.
